site_name: supergreen
description: Analyze errors in tabular data ML models systematically.
theme:
  name: material
  palette:
    primary: green
    accent: indigo
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate 
    - toc.follow
    - navigation.top
  icon:
    repo: fontawesome/brands/github 
repo_url: https://github.com/supergreenai/supergreen
markdown_extensions:
  - admonition
  - tables
plugins:
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
